//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service_Reader
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceDay
    {
        public int Id { get; set; }
        public System.DateTime TravelStartTime { get; set; }
        public System.DateTime ArrivalOnsiteTime { get; set; }
        public System.DateTime DepartureSiteTime { get; set; }
        public System.DateTime TravelEndTime { get; set; }
        public int Mileage { get; set; }
        public int DailyAllowance { get; set; }
        public int OvernightAllowance { get; set; }
        public int BarrierPayment { get; set; }
        public double TravelToSiteTime { get; set; }
        public double TravelFromSiteTime { get; set; }
        public double TotalTravelTime { get; set; }
        public double TotalOnsiteTime { get; set; }
        public string DailyReport { get; set; }
        public string PartsSuppliedToday { get; set; }
        public System.DateTime DtReport { get; set; }
        public Nullable<int> ServiceSheetId { get; set; }
    
        public virtual ServiceSheet ServiceSheet { get; set; }
    }
}
