//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service_Reader
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ServiceSheetsEntities : DbContext
    {
        public ServiceSheetsEntities()
            : base("name=ServiceSheetsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CanvasHistoricalData> CanvasHistoricalDatas { get; set; }
        public virtual DbSet<CanvasRawData> CanvasRawDatas { get; set; }
        public virtual DbSet<ServiceDay> ServiceDays { get; set; }
        public virtual DbSet<ServiceSheet> ServiceSheets { get; set; }
    
        public virtual int CreateServiceTables()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CreateServiceTables");
        }
    }
}
